### PR TITLE
Player

### PR DESCRIPTION
**Pull request by BlazyBg**

### CODE REVIEW

**Review by HarryBGamer2570 — CHANGES_REQUESTED** [review]
no playermovement, ne struvash

**Review by HarryBGamer2570 — CHANGES_REQUESTED** [review]
zabravi da zakachaish kamerata, sakvash

**Review by HarryBGamer2570 — CHANGES_REQUESTED** [review]
use time not fps :/

**Review by HarryBGamer2570 — APPROVED** [review]
works :)













































sakvash :(

**Review by RockB0Y — APPROVED** [review]
Looks good

**Pull request merged**
